services:
  chaos-api:
    build:
      context: ./app
    container_name: chaos-api
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: chaos-prometheus
    depends_on:
      - chaos-api
      - alertmanager
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: chaos-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
